site_name: 'Arriba'
site_description: 'Fast and accurate gene fusion detection from RNA-Seq data'
site_author: 'Sebastian Uhrig'
site_url: 'https://github.com/suhrig/arriba/'
repo_url: 'https://github.com/suhrig/arriba/'
docs_dir: 'documentation'
theme: 'readthedocs'
pages:
  - 'Home': 'index.md'
  - 'quickstart.md'
  - 'workflow.md'
  - 'input-files.md'
  - 'output-files.md'
  - 'visualization.md'
  - 'command-line-options.md'
  - 'interpretation-of-results.md'
  - 'current-limitations.md'
  - 'internal-algorithm.md'
